<a href="https://colab.research.google.com/github/RatchanonPa/Data-Warehouse-and-Big-Data-Analytics/blob/main/LLMs_Hackathon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.11/dist-packages (1.7.4.2)
Requirement already satisfied: bleach in /usr/local/lib/python3.11/dist-packages (from kaggle) (6.2.0)
Requirement already satisfied: certifi>=14.05.14 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2025.4.26)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.4.2)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from kaggle) (3.10)
Requirement already satisfied: protobuf in /usr/local/lib/python3.11/dist-packages (from kaggle) (5.29.4)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.11/dist-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.32.3)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.11/dist-packages (from kaggle) (75.2.0)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.17.0)
Requirement already satisfied: text-unidecode in /usr/local/lib/python3.11/dist-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (from kaggle) (4.67.1)
Requirement already satisfied: urllib3>=1.15.1 in /usr/local/lib/python3.11/dist-packages (from kaggle) (2.4.0)
Requirement already satisfied: webencodings in /usr/local/lib/python3.11/dist-packages (from kaggle) (0.5.1)

In [2]:
import os
import shutil

# อัปโหลด kaggle.json
from google.colab import files
files.upload()  # จะให้คุณเลือกไฟล์ kaggle.json ที่โหลดมา

# สร้างโฟลเดอร์ ~/.kaggle ถ้ายังไม่มี
os.makedirs("/root/.kaggle", exist_ok=True)

# ย้ายไฟล์ไปยังโฟลเดอร์ที่ต้องการ
shutil.move("kaggle.json", "/root/.kaggle/kaggle.json")

# ตั้งสิทธิ์การเข้าถึง
os.chmod("/root/.kaggle/kaggle.json", 600)

Saving kaggle.json to kaggle.json

In [3]:
!kaggle competitions download -c crime-charges-analysis

In [4]:
!unzip /content/crime-charges-analysis.zip

Archive:  /content/crime-charges-analysis.zip
  inflating: classes.xlsx
  inflating: submission.csv
  inflating: train.csv

In [5]:
# Discussed conceptually (from PDF notes) and usually run in Colab
!pip install transformers
!pip install datasets
!pip install evaluate -U # -U for upgrade
!pip install accelerate -U
!pip install sentencepiece # For tokenizers like SentencePiece
!pip install gdown # For downloading files from Google Drive

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.51.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.18.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.30.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.31.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.3)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (2025.3.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (4.13.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers) (1.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2025.4.26)
Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (2.14.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.8,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.15)
Requirement already satisfied: fsspec>=2021.11.1 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.11.1->datasets) (2025.3.2)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.15)
Requirement already satisfied: huggingface-hub<1.0.0,>=0.14.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.31.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.20.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0.0,>=0.14.0->datasets) (3.18.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0.0,>=0.14.0->datasets) (4.13.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0.0,>=0.14.0->datasets) (1.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->datasets) (2025.4.26)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Collecting evaluate
  Downloading evaluate-0.4.3-py3-none-any.whl.metadata (9.2 kB)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.14.4)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.0.2)
Requirement already satisfied: dill in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.3.7)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.11/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.70.15)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2025.3.2)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.31.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from evaluate) (24.2)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (18.1.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.11.15)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate) (3.18.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.13.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate) (1.1.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2025.4.26)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.6.1)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.6.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.4.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.20.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Downloading evaluate-0.4.3-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 3.6 MB/s eta 0:00:00
Installing collected packages: evaluate
Successfully installed evaluate-0.4.3
Requirement already satisfied: accelerate in /usr/local/lib/python3.11/dist-packages (1.6.0)
Requirement already satisfied: numpy<3.0.0,>=1.17 in /usr/local/lib/python3.11/dist-packages (from accelerate) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from accelerate) (24.2)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/dist-packages (from accelerate) (6.0.2)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from accelerate) (2.6.0+cu124)
Requirement already satisfied: huggingface-hub>=0.21.0 in /usr/local/lib/python3.11/dist-packages (from accelerate) (0.31.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.11/dist-packages (from accelerate) (0.5.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.21.0->accelerate) (3.18.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.21.0->accelerate) (2025.3.2)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.21.0->accelerate) (2.32.3)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.21.0->accelerate) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.21.0->accelerate) (4.13.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.21.0->accelerate) (1.1.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=2.0.0->accelerate)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=2.0.0->accelerate)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=2.0.0->accelerate)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=2.0.0->accelerate) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (3.4.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->huggingface-hub>=0.21.0->accelerate) (2025.4.26)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.5 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 122.6 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 94.3 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 64.8 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.6 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.6 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 19.8 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.4 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.8 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 106.2 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:

In [6]:
gpu_info = !nvidia-smi
gpu_info = '\n'.join(gpu_info)
if gpu_info.find('failed') >= 0:
  print('Not connected to a GPU')
else:
  print(gpu_info)

Mon May 12 16:17:15 2025
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   33C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [6]:
import pandas as pd

train_df = pd.read_csv('/content/train.csv')
class_df = pd.read_excel('/content/classes.xlsx') # Corrected function name
test_df = pd.read_csv('/content/submission.csv')

In [7]:
train_df

,id,story,answers
0,OhbVrpoiVg,จุงลิ่วขโมยรถจักรยานยนต์จากลานจอด ขณะที่แคสใช้...,"[{'จุงลิ่ว': '[2]'}, {'แคส': '[2,5]'}]"
1,RV5IfLBcbf,จิรศักก์กำลังทำอาหารอยู่ในครัว ในขณะที่ไขนภาเด...,"[{'จิรศักก์': '[1]'}, {'ไขนภา': '[1]'}]"
2,noGMbJmTPS,คมกาญจน์ขโมยเงินสดจากตู้อัตโนมัติในห้างและบุกร...,"[{'คมกาญจน์': '[2,4,5]'}, {'จิรานุวัตร': '[6]'}]"
3,IAoCLrZ3aW,ขจรพงค์ปล่อยให้ระบบลิฟต์โรงแรมขัดข้องจนตกลงมาพ...,[{'ขจรพงค์': '[3]'}]
4,ZkSBvrjn9W,กิมใจยิงเจ้าหน้าที่ขนส่งเสียชีวิตขณะนำของเข้าร...,"[{'กิมใจ': '[2,5,7]'}, {'ขนิฐชีพ': '[5]'}]"
...,...,...,...
1795,uHkBogTZiG,กิติยวดีใช้อาวุธไฟฟ้าช็อต รปภ. ก่อนบุกรุกห้างแ...,"[{'กิติยวดี': '[2,4,5]'}, {'เจติญา': '[2]'}]"
1796,hOKYz1WO6q,กำไลกับจิรวงษ์โจรกรรมในตลาดกลางคืน,"[{'กำไล': '[2]'}, {'จิรวงษ์': '[2]'}]"
1797,1Jk8unffbB,แจ้งฮ้งกำลังนั่งทำการบ้านอยู่ที่บ้านขณะที่ง่วน...,"[{'แจ้งฮ้ง': '[1]'}, {'ง่วนเส็ง': '[1]'}]"
1798,aOXLjbNTI6,จิตต์เกื้อซ่อนมีดในเบาะรถของเกษยุราแล้วจงใจเบร...,"[{'เกษยุรา': '[1]'}, {'จิตต์เกื้อ': '[5,7]'}]"
1799,fKybVUiDOO,เกียรติประพันธ์ฉ้อโกงเงินจากลูกค้าผ่านระบบออนไ...,"[{'เกียรติประพันธ์': '[6]'}, {'เจตะนิพัทธิ์': ..."

In [31]:
class_df

   Class                                        Description
0      1    ไม่มีความผิดหรือไม่มีความเกี่ยวข้องกับเหตุการณ์
1      2                             ลักทรัพย์หรือชิงทรัพย์
2      3  กระทำการใดๆด้วยความประมาทหรือละเลยส่งผลให้เกิด...
3      4               บุกรุกเข้าเขตหวงห้ามหรือนอกเวลาทำการ
4      5  กระทำการใดๆด้วยเจตนาที่ส่งผลให้เกิดความเสียหาย...
5      6  ฉ้อโกงประชาชน, ปลอมแปลงเอกสาร หรือปลอมแปลงสิ่ง...
6      7                    ทำให้มีคนตายด้วยวิธีการใดๆก็ตาม

In [32]:
test_df

,id,story,answers
0,XwlpP5otmI,เคี้ยนแพ้หมากรุกเลยชักปืนขึ้นมายิงจราจนเสียชีวิต,"[{'เคี้ยน': '[5,7]'}, {'จรา': '[1]'}]"
1,1pUXZYyXqQ,จิดาพัฒน์ยิงปืนเล่นน้ำสงกรานต์,[{'จิดาพัฒน์': '[1]'}]
2,drf7jObOL3,กรัณยพรขับรถเมาแล้วชนรถบัสในสถานีขนส่ง ส่งผลให...,"[{'กรัณยพร': '[3,7]'}]"
3,ghD7Mhgjsq,คำนึงภัชทุจริตในการจัดซื้อวัสดุโรงเรียนและปลอม...,NaN
4,5lfeF2x61n,กอบเกิดขับรถขณะหลับในช่วงกลางวัน ทำให้รถพุ่งข้...,NaN
...,...,...,...
995,wEWpIvFoB9,กิมฮัวฉ้อโกงเงินจากลูกค้าผ่านเว็บไซต์ปลอมในงาน...,NaN
996,JbSegK5ioA,กุศลินีบุกรุกเข้าโรงพยาบาล ขโมยยาและทำร้ายพยาบ...,NaN
997,3cnDAIVegR,กลินธ์ขับรถประมาทในการแข่งจนเกิดอุบัติเหตุร้ายแรง,NaN
998,JCTioVnnxg,กชญาณสร้างบริษัทอสังหาริมทรัพย์ปลอม ส่วนจิราทิ...,NaN
999,cqa6LAhrPL,เกษฉราภรณ์ขับรถเมาแล้วชนคนเดินเท้าในซอย,NaN

In [8]:
import pandas as pd
import ast # For safely evaluating string-represented lists/dicts
from sklearn.preprocessing import MultiLabelBinarizer # For multi-hot encoding

def parse_answers(answer_str):
    if pd.isna(answer_str):
        return []
    try:
        # Safely evaluate the string as a Python literal (list of dicts)
        answers_list = ast.literal_eval(answer_str)
        all_class_ids = set()
        for ans_dict_list in answers_list: # [{'จุงลิ่ว': '[2]'}, {'แคส': '[2,5]'}]
            for entity_ans in ans_dict_list.values(): # e.g., '[2,5]'
                class_ids_str = ast.literal_eval(entity_ans) # e.g., [2,5]
                for class_id in class_ids_str:
                    all_class_ids.add(int(class_id)) # Make sure they are integers
        return sorted(list(all_class_ids))
    except (ValueError, SyntaxError):
        return [] # Handle cases where parsing fails

train_df['parsed_labels'] = train_df['answers'].apply(parse_answers)
train_df

,id,story,answers,parsed_labels
0,OhbVrpoiVg,จุงลิ่วขโมยรถจักรยานยนต์จากลานจอด ขณะที่แคสใช้...,"[{'จุงลิ่ว': '[2]'}, {'แคส': '[2,5]'}]","[2, 5]"
1,RV5IfLBcbf,จิรศักก์กำลังทำอาหารอยู่ในครัว ในขณะที่ไขนภาเด...,"[{'จิรศักก์': '[1]'}, {'ไขนภา': '[1]'}]",[1]
2,noGMbJmTPS,คมกาญจน์ขโมยเงินสดจากตู้อัตโนมัติในห้างและบุกร...,"[{'คมกาญจน์': '[2,4,5]'}, {'จิรานุวัตร': '[6]'}]","[2, 4, 5, 6]"
3,IAoCLrZ3aW,ขจรพงค์ปล่อยให้ระบบลิฟต์โรงแรมขัดข้องจนตกลงมาพ...,[{'ขจรพงค์': '[3]'}],[3]
4,ZkSBvrjn9W,กิมใจยิงเจ้าหน้าที่ขนส่งเสียชีวิตขณะนำของเข้าร...,"[{'กิมใจ': '[2,5,7]'}, {'ขนิฐชีพ': '[5]'}]","[2, 5, 7]"
...,...,...,...,...
1795,uHkBogTZiG,กิติยวดีใช้อาวุธไฟฟ้าช็อต รปภ. ก่อนบุกรุกห้างแ...,"[{'กิติยวดี': '[2,4,5]'}, {'เจติญา': '[2]'}]","[2, 4, 5]"
1796,hOKYz1WO6q,กำไลกับจิรวงษ์โจรกรรมในตลาดกลางคืน,"[{'กำไล': '[2]'}, {'จิรวงษ์': '[2]'}]",[2]
1797,1Jk8unffbB,แจ้งฮ้งกำลังนั่งทำการบ้านอยู่ที่บ้านขณะที่ง่วน...,"[{'แจ้งฮ้ง': '[1]'}, {'ง่วนเส็ง': '[1]'}]",[1]
1798,aOXLjbNTI6,จิตต์เกื้อซ่อนมีดในเบาะรถของเกษยุราแล้วจงใจเบร...,"[{'เกษยุรา': '[1]'}, {'จิตต์เกื้อ': '[5,7]'}]","[1, 5, 7]"
1799,fKybVUiDOO,เกียรติประพันธ์ฉ้อโกงเงินจากลูกค้าผ่านระบบออนไ...,"[{'เกียรติประพันธ์': '[6]'}, {'เจตะนิพัทธิ์': ...","[2, 4, 6]"

In [9]:
# Use MultiLabelBinarizer to create multi-hot encoded vectors
# Define all possible class IDs (0 to 7 based on class_df)
all_possible_classes = list(range(8)) # Assuming classes are 0-7

mlb = MultiLabelBinarizer(classes=all_possible_classes)
train_labels_multi_hot = mlb.fit_transform(train_df['parsed_labels'])

In [10]:
train_labels_multi_hot

array([[0, 0, 1, ..., 1, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 1, 1, 0],
       ...,
       [0, 1, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 0, 1, 0]])

In [11]:
# Add these multi-hot labels back to the DataFrame (optional, but can be useful)
# For direct use with Hugging Face, we might pass this array directly or format it
# For simplicity in this example, let's just keep `parsed_labels` for now
# and assume the model will handle multi-label output.

# For test_df, if you have some answers, process them similarly
# If test_df 'answers' are mostly NaN, you'll predict and then evaluate externally
if 'answers' in test_df.columns:
    test_df['parsed_labels'] = test_df['answers'].apply(parse_answers)
    # test_labels_multi_hot = mlb.transform(test_df['parsed_labels']) # Don't fit again!

In [12]:
# The 'story' column becomes the text input
train_texts = train_df['story'].tolist()
# Convert train_labels_multi_hot to a list of lists of floats for Hugging Face
train_labels_for_hf = [list(map(float, row)) for row in train_labels_multi_hot]

In [14]:
train_texts

['จุงลิ่วขโมยรถจักรยานยนต์จากลานจอด ขณะที่แคสใช้ปืนจี้ชิงเงินสดจากสถานีขนส่ง',
 'จิรศักก์กำลังทำอาหารอยู่ในครัว ในขณะที่ไขนภาเดินตกบันไดด้วยความประมาทส่งผลให้ตนเองขาหัก',
 'คมกาญจน์ขโมยเงินสดจากตู้อัตโนมัติในห้างและบุกรุกเข้าหลังร้านเพื่อขโมยของ มีผลให้เกิดความเสียหายต่อทรัพย์สิน ขณะที่จิรานุวัตรฉ้อโกงผ่านโทรศัพท์',
 'ขจรพงค์ปล่อยให้ระบบลิฟต์โรงแรมขัดข้องจนตกลงมาพร้อมผู้โดยสาร',
 'กิมใจยิงเจ้าหน้าที่ขนส่งเสียชีวิตขณะนำของเข้าร้านทอง และขโมยทองที่บรรทุกมา ส่วนขนิฐชีพทุบทำลายกล้องวงจรปิดด้วยความสะใจเฉยๆ',
 'ขวัญอรุณวางเพลิงอาคารเก่าทำให้ทรัพย์สินเสียหาย และลักทรัพย์ในห้องควบคุม',
 'จิรเวทพิมพ์ผิดรหัสฉุกเฉิน ทำให้ระบบแจ้งเตือนหยุดทำงาน',
 'กาญจน์อรยิงผู้รักษาความปลอดภัยจนเสียชีวิต ขณะที่ขวัญอมรลักบัตรผ่านเข้าออกอาคารและขโมยเอกสารภายใน',
 'กานดาศรีลอบบุกรุกเข้าห้องเก็บของในอาคารและขโมยโทรศัพท์ออกไปในคืนวันหยุด ขณะที่กิมหุนฉ้อโกงนักลงทุนด้วยเอกสารปลอม',
 'กฤติภรใช้มีดข่มขู่ในงานเลี้ยงโรงแรมและทำให้ฝ่ายที่เกี่ยวข้องบาดเจ็บอย่างรุนแรง ขณะที่จำเป็นศรีขโมยของจากตลาดนัดด้วยการบุกรุก',
 'เกรียงกิตอ้างว่าสามารถต่อทะเบียนรถล่วงหน้าได้ราคาถูกเพื่อหลอกเงินค่าดำเนินการ',
 'จิรวิชณน์ฝันว่าเป็นโจรชิงทรัพย์ข้างบ้าน',
 'เกียฮี้ปลอมเอกสารเบิกงบราชการและลักเงินจากกองทุนหมู่บ้าน ขณะที่เกษสิริใช้อาวุธมีดข่มขู่เจ้าหน้าที่ฝ่ายบัญชี',
 'เจษฎาพรพาเพื่อนไปเที่ยวชมวัดวาอาราม',
 'คล้ายเครือขับรถเมาชนรถกระบะจนเกิดอุบัติเหตุรุนแรง',
 'ก๊วยตังปลอมบัญชีเงินเดือนและยักยอกเงินองค์กร พร้อมกับบุกรุกเข้าไปในช่วงกลางคืน',
 'กรุงบอกให้คนอื่นออกจากบ้าน และเมื่ออยู่ลำพังกับคมกฤตเขาใช้ปืนพกยิงเธอที่หน้าอก 2 นัดจนเธอเสียชีวิตทันที',
 'แก่เล่นชิงช้าสวรรค์',
 'กิตติสันต์ใช้ตำแหน่งในบริษัทเพื่อแอบฉ้อโกงเงินจากกองทุนสวัสดิการของพนักงานด้วยการปลอมเอกสารและเปลี่ยนแปลงบัญชีธนาคารโดยเจตนา',
 'จันทร์ธรใช้มีดข่มขู่คู่แข่งในตลาดแล้วชิงเงินสดจากพ่อค้ารายเล็ก',
 'กวิสสรขโมยเงินจากตู้อัตโนมัติและบุกรุกเข้ามาในอาคาร',
 'ในงานประชุมองค์กร เครนบุกรุกเข้าห้องประชุมและขโมยแฟ้มลับออกไป ขณะที่กวินภศฉ้อโกงนักลงทุนด้วยเอกสารปลอม',
 'กัลย์รัตน์ใช้มีดคุกคามประชาชนในตลาดและขโมยกระเป๋าจากผู้คนในเวลาเดียวกัน',
 'จุมาศลอบบุกรุกเข้าศูนย์การค้าที่มีระบบรักษาความปลอดภัยสูงและขโมยเครื่องประดับออกไปในคืนที่มืดมิด',
 'จิตตกาลแอบบุกรุกเข้าบ้านจันทร์อำพรในเวลาที่เขาออกไปทำงาน พร้อมทั้งขโมยเครื่องประดับมีค่าออกไป',
 'คุ้มพันธ์ขับรถเมาแล้วชนคนเดินเท้าในงานตลาด ทำให้หลายคนบาดเจ็บ',
 'กริษสุดาขโมยของจากร้านสะดวกซื้อโดยบุกรุกเข้ามาทางด้านหลังและขโมยของมีค่า',
 'คำพ้วยลอบบุกรุกร้านชำแล้วขโมยสินค้าหลากหลายชนิดออกไปก่อนขนิษฐพรสังเกตเห็น',
 'คติชัยขับรถฝ่าไฟแดงและพุ่งชนรถของกัณยาณิษฐ์ที่วิ่งมาถูกทางจนรถพังเสียหาย',
 'กรัณฑฤทธิฉ้อโกงประชาชนผ่านการส่งอีเมลปลอมในงานสัมมนา ทำให้ผู้ลงทุนขาดทุน',
 'จันทภาสปลอมเอกสารโอนบ้าน ส่วนกรุซารันซิงห์แกล้งเป็นทนายรับรองเอกสารหลอกเหยื่อให้จ่ายเงินค่าดำเนินการ',
 'จิระภาคย์ หลอกว่ามีญาณทิพย์สามารถเห็นล็อตเตอรี่ที่จะออกเดือนนี้ได้ โดยจะบอกก็ต่อเมื่อนำเงินมาให้ 500บาท ซึ่งมีคนหลงเชื่อมากมาย',
 'กมลนัยบุกรุกเข้าโรงเรียนตอนกลางคืนเพื่อลักทรัพย์ ส่วนขวัญเชิญใช้อาวุธปืนไล่เจ้าหน้าที่รักษาความปลอดภัย',
 'คำเคนบุกรุกเข้าร้านอาหารและขโมยเงินสดจากตู้อัตโนมัติ',
 'จิรวิศิษฏ์ป้ายยาพิษลงบนแปรงสีฟันของกลิ่นขจรหลังจากใช้เพียงสองครั้ง เธอเสียชีวิตจากพิษตกค้าง',
 'คลำขโมยกระเป๋าสตางค์และโทรศัพท์จากผู้โดยสารในรถไฟฟ้าด้วยการแอบเข้ามาในที่จอดรถ',
 'จิตเจริญยิงผู้รักษาความปลอดภัยจนเสียชีวิตในลานจอดรถ ขณะที่เกื้อกาญจน์ชิงทรัพย์กระเป๋าเงินจากผู้เสียหาย',
 'ก้องการ์รุนต์บุกรุกเข้าสำนักงานและขโมยเอกสาร',
 'จตุการเปิดคอร์สสอนเทรดหุ้นปลอม ส่วนเกศราภรณ์แกล้งเป็นลูกศิษย์ที่ได้กำไรมหาศาล',
 'กันตนัชพลษ์นำสุนัขพันธุ์ดุไปเดินในสวนสาธารณะโดยไม่ใส่สายจูง จนสุนัขกัดจิระเวชบาดเจ็บ',
 'เกริกบุญยิงปืนใส่คู่ต่อสู้ในเกม',
 'จะรวยลอบเข้าโกดังขนส่งและขโมยพัสดุพร้อมปลอมเอกสารส่งของ ขณะเกตุมณีย์แอบขโมยเงินในสำนักงาน',
 'กัญญุมณฑ์มีปากเสียงกับจิ้นเกียงอย่างรุนแรง และในช่วงที่เขาเผลอ เธอคว้ามีดในครัวมาแทงเขาหลายครั้งจนถึงแก่ความตาย',
 'กัญยารัตน์ใช้ปืนข่มขู่และยิงฆ่าผู้คนในงานคอนเสิร์ต ขณะที่กุ้ยกี่ขโมยของมีค่าในช่วงชุลมุน',
 'กันต์กานต์ซ่อมเครื่องจักรในโรงงานโดยไม่ปิดสวิตช์หลัก ทำให้คำพองทิพย์ถูกเครื่องหนีบมือขาด',
 'คำไมล์หลอกขายทองปลอมผ่านออนไลน์ ส่วนจันทร์พรส์แกล้งเป็นลูกค้าเก่าที่ได้ทองจริง กษิภพโอนเงินซื้อ',
 'จีระพัชร์ยิงครองสิญจ์ที่หน้าผากขณะเธอเปิดประตูบ้านจนเสียชีวิต',
 'ครีนภัทรขับรถเมาแล้วชนกับรถตุ๊กตุ๊กบนทางหลวง ส่งผลให้ผู้เดินถนนเสียชีวิต',
 'จามิกรชิงทรัพย์ทองรูปพรรณจากงานวัด ขณะที่ควงฤทธิ์ฉ้อโกงเงินค่าพิธีด้วยเอกสารกลางคืน',
 'กรรณธิมาผลักขวัญญานันท์ออกนอกหน้าต่างชั้น 8 ขณะเธอยืนสูบบุหรี่ไฟฟ้า ทำให้เธอตกลงมาเสียชีวิต',
 'แคทร์ทรีขโมยฮาร์ดดิสก์จากค่ายเกม ขณะที่กันรัตน์ฉ้อโกงเงินผู้ใช้ผ่านระบบเติมเกมปลอม',
 'กัญญาเพ็ญและเกษีบุกเข้าไปในสำนักงานเทศบาลในตอนกลางคืนเพื่อขโมยอุปกรณ์สำนักงาน',
 'ขันธวุฒิลอบบุกรุกเข้าร้านเครื่องประดับและขโมยของมีค่าออกไป ในขณะเดียวกันเขตฤทัยขโมยของจากร้านอาหารที่ไกลออกไป',
 'คมฉัตรวางแผนฆ่าหญิงสาวที่สามีแอบมีความสัมพันธ์ด้วย โดยใช้มีดแทงเสียชีวิต',
 'ครองจิตรใช้ปืนคุกคามในงานแสดงสินค้าที่จัดขึ้นในห้างใหญ่ และยิงฆ่าผู้บริสุทธิ์ที่พยายามต่อต้านระหว่างการจัดงาน',
 'จาเรปล้นของจากตลาดนัดด้วยการข่มขู่และทำร้ายเจ้าของร้าน ขณะที่ครุศิลป์ฉ้อโกงผ่านเว็บไซต์ปลอม',
 'จันทรชิตใช้กระทะฟาดหัวขวัญธีราระหว่างหลับจนเสียชีวิต',
 'กฤษณะชัยขับรถเมาแล้วชนรถโดยสารในงานเทศกาลด้วยความประมาทจนนำไปสู่อุบัติเหตุร้ายแรง',
 'เจริญชายลอบบุกรุกเข้าไปในห้องทดลองของโรงงานเคมีในยามค่ำคืน โดยใช้เครื่องมือเจาะประตูและขโมยสูตรเคมีลับที่บริษัทเก็บรักษาไว้อย่างพิถีพิถัน',
 'โฆษพงศ์ขโมยของมีค่าจากตลาดนัด ขณะที่เขมรุจิฉ้อโกงเงินจากระบบการเงินด้วยเอกสารปลอม',
 'ขลิบเพชรยิงเจ้าหน้าที่ป่าไม้เสียชีวิตขณะหลบหนีจากการลักลอบขนไม้ผิดกฎหมาย ส่วนกจัดกาญจน์เป็นผู้ขับรถให้',
 'กรรณเกศใช้มีดแทงพนักงานร้านสะดวกซื้อหลายแผลจนเสียชีวิต',
 'จุลลดาโดนเจตนาพรใช้มีดโจมตีที่งานเลี้ยง และทำให้เกิดบาดแผลสาหัส',
 'ก๋องฉ้อโกงเงินจากลูกค้าผ่านเว็บไซต์ปลอมในงานสัมมนา',
 'คุณสิทธิ์บุกรุกร้านอาหารและเปิดปืนยิงฆ่าลูกค้าขณะรับประทาน',
 'เกษมพิพัฒน์ฉ้อโกงประชาชนในงานเปิดตัวสินค้าโดยใช้เอกสารปลอม',
 'เกตุวิลัยขโมยกระเป๋าจากรถโดยสาร',
 'ครองชัยก่อสร้างบ้านโดยไม่ปิดกั้นพื้นที่ให้ดี ทำให้วัสดุตกใส่รถยนต์ของคนอื่นได้รับความเสียหาย',
 'คกเท่าปลอมบัตรประชาชนเพื่อขอเงินเยียวยา และขโมยเครื่องใช้ไฟฟ้าจากสำนักงานรัฐ ขณะที่กฤตย์ธวรรณบุกรุกสำนักงานกลางดึก',
 'เกริกกรรณแทงคมน์กฤตย์ที่หลัง 2 ครั้งขณะเขากำลังเก็บของจากท้ายรถจนเสียชีวิต',
 'คุณดิฐบอกกับกรพชรว่าเธอติดโรคร้ายแรงจากเขา แล้วใส่ยานอนหลับในอาหารให้เขาหลับ ก่อนใช้มีดกรีดข้อมือเขาจนถึงแก่ความตาย',
 'เกณิศาใช้มีดโจมตีผู้คนในงานเลี้ยงโรงแรมและยิงฆ่าผู้คน ขณะที่ขวัญโสมบุกรุกเข้าบ้านคนแล้วขโมยของออกไป',
 'กิตธิชัยขโมยเอกสารลับจากสำนักงานโดยบุกรุกและเกี๋ยงภาใช้มีดข่มขู่เพื่อชิงทรัพย์จากผู้เข้าประชุม',
 'คัมภีย์ลอบบุกรุกเข้าร้านเสื้อผ้าและขโมยสินค้าหลากหลายรายการ',
 'เจตษรินทร์บุกรุกเข้าร้านอาหารและขโมยเงินสดจากตู้อัตโนมัติในเวลากลางคืน ขณะที่จังเว้งใช้มีดโจมตีผู้คนในงานเลี้ยงทำให้ขวัญนรีบาดเจ็บสาหัส',
 'กฤติธรใช้ก้อนหินทุบศีรษะขจิตศิริซ้ำหลายครั้งที่ชายหาดจนเขาเสียชีวิต',
 'แก้วมลไม่ปิดเครื่องขุดขณะหยุดพัก ทำให้เครื่องเคลื่อนชนคนงาน',
 'กรรจนีประมาทปล่อยให้สารเคมีตกค้างในถังอาหาร ทำให้ผู้บริโภคเสียชีวิต',
 'คนาชัยขับรถเมาแล้วชนรถในงานตลาด ทำให้เกิดความเสียหายต่อทรัพย์สิน',
 'เกียรติเมธส์ลอบเข้าโรงเรียนเวลากลางคืนเพื่อขโมยคอมพิวเตอร์ ขณะที่กิจรักษ์ปลอมเอกสารสั่งซื้อ',
 'กุณทินีฉ้อโกงเงินจากการลงทุนในโครงการปลอมผ่านอินเทอร์เน็ต',
 'กีรฏิใช้อาวุธปืนขึ้นมาขู่ผู้คนและยิงกีฬธินในที่สาธารณะจนเสียชีวิต',
 'กันกนิษฐ์จัดตั้งโครงการปลอมแปลงสัญญาและเผยแพร่ข้อมูลเท็จในอินเทอร์เน็ตเพื่อหลอกลวงประชาชนให้ลงทุนในโครงการที่ไม่มีอยู่จริง จนทำให้ผู้ลงทุนสูญเสียเงินจำนวนมาก',
 'กุลวิชจัดโครงการลงทุนปลอมหลวงหลอกลวงประชาชนในงานเทศกาล ทำให้ผู้ลงทุนสูญเสียเงินจำนวนมาก',
 'ฆนญานีใช้เครื่องจักรโดยไม่อบรม ทำให้เกิดอุบัติเหตุแรงงานขาขาด',
 'ครองรัชฏ์ปลอมเอกสารการซื้อขายที่ดินเพื่อหลอกเอาเงินผู้สูงอายุ ส่วนจุติมาพรลักของจากบ้านเหยื่อ',
 'จินดาวรรณฉ้อโกงเงินจากนักลงทุนด้วยเอกสารปลอมและบุกรุกเข้าห้องประชุมเพื่อขโมยแฟ้มลับ ขณะที่ขนาณขโมยของจากร้านค้า',
 'กัลยธรณ์ใช้มีดโจมตีคนิตาในงานเลี้ยง ทำให้ฝ่ายตรงข้ามบาดเจ็บสาหัส ขณะที่ไข่ศรีขโมยกระเป๋าจากรถโดยสาร',
 'จีลาพรฉ้อโกงลูกค้าผ่านการปลอมแปลงข้อมูลในงานสัมมนา ทำให้ผู้ลงทุนขาดทุน',
 'กุพชกาเป็นนักพัฒนาแอปที่ช่วยคุณภัฏสร้างแอปสำหรับคนพิการทางสายตา โดยร่วมทดสอบและแก้ไขข้อบกพร่องจนแอปใช้งานได้ดี',
 'กิจจาภาขับรถเมาแล้วชนกับคนเดินในตรอกแคบ ทำให้เกิดอุบัติเหตุรุนแรง',
 'กลพจน์ถูกจับในคดีชิงทรัพย์เมื่อลอบแย่งกระเป๋าจากผู้หญิงในตลาดที่คนพลุกพล่าน',
 'กฤชนนท์ฉ้อโกงผู้บริโภคผ่านโฆษณาปลอม',
 'กาซิมและเกวิภาเป็นนักเรียนที่ได้รับเลือกเป็นตัวแทนโรงเรียนเข้าร่วมแข่งขันตอบปัญหาวิทยาศาสตร์',
 'กาญชณาลอบบุกรุกเข้าศูนย์ข้อมูลบนชั้นใต้ดินและขโมยฮาร์ดไดรฟ์เก็บข้อมูลสำคัญ ขณะที่กฤชษฎาใช้อาวุธข่มขู่ลูกค้าในร้านกาแฟเพื่อชิงทรัพย์',
 'ครวญและจันทร์ดาร่วมกันพัฒนาแอปพลิเคชันช่วยคนตาบอดอ่านฉลากสินค้า โดยไม่มีการละเมิดลิขสิทธิ์หรือกฎหมาย',
 'จันทร์ดับหลอกให้กอบกาลปีนหลังคาไปซ่อมสายไฟ แล้วตัดเชือกนิรภัยทำให้เขาตกลงมาเสียชีวิต',
 'จิตติภัสสั่งเปิดระบบรดน้ำอัตโนมัติขณะมีงานกลางแจ้ง ทำให้อุปกรณ์เปียก',
 'กิมเล็งชิงชัง เคียกฟ้าเพราะไม่ได้มรดกตามที่หวังไว้',
 'กฤชรัชใช้มีดข่มขู่ผู้คนในงานคอสเพลย์และแทงเจ้าหน้าที่ที่เข้ามาห้ามจนเสียชีวิต',
 'เกริกพรปล่อยให้น้ำมันหกในห้างสรรพสินค้าโดยไม่ทำความสะอาดหรือติดป้ายเตือน ทำให้จำรัชลื่นล้มขาหัก',
 'กุลพันธุ์ทำทีว่าต้องการขอโทษจิมเรื่องอดีต ก่อนจะพาเธอไปจุดชมวิวแล้วผลักเธอลงจากหน้าผาทันที เธอเสียชีวิตคาที่',
 'เจตวรินทร์เชิญจิตกาญจน์ไปงานแต่งงานของพี่สาว โดยทั้งสองร่วมงานในฐานะแขก ไม่มีเหตุวุ่นวายหรือผิดกฎหมายใดๆ',
 'จิยพงษ์ใช้มีดทำครัวแทงคุณธิดาที่หน้าอกหลายครั้งหลังจากทะเลาะกัน ทำให้เขาเสียชีวิต',
 'จิตรสราลอบสอดยาพิษใส่น้ำดื่มของจีระวรรณ์จนเสียชีวิต',
 'กีฟฉ้อโกงเงินจากลูกค้าออนไลน์',
 'กำรูญใส่เศษแก้วลงในอาหารของกันต์ปวีร์ขณะเขากำลังกิน จนเขาเสียชีวิตจากบาดแผลในลำคอและหลอดอาหาร',
 'จุ่งหมงวางแผนใช้สารพิษในอาหารเช้าให้กัญจน์ปิษฎากินจนเสียชีวิตโดยไม่ทันรู้ตัว',
 'คุณาพจน์เป็นนักวิจัยในหน่วยงานราชการ แต่กลับลอบฆ่าจิตตสักก์ซึ่งเป็นหัวหน้าที่ไม่อนุมัติงานของเธอ ด้วยการผสมสารเคมีลงในน้ำดื่มของเขาจนเสียชีวิต',
 'คชบงขับรถเมาแล้วชนรถส่วนตัวจนผู้โดยสารเสียชีวิต',
 'กรีติและกิ้มซ้วนเข้าร่วมคอร์สเรียนทำอาหารไทยที่เปิดสอนสำหรับชาวต่างชาติ ไม่มีสิ่งผิดกฎหมาย',
 'กัญจญารัตน์เชิญคันธวัลย์มาร่วมเวิร์กช็อปอบรมทำสบู่สมุนไพรในหมู่บ้าน ทั้งสองคนช่วยกันจัดเตรียมวัสดุและสาธิตแก่ผู้ร่วมกิจกรรม',
 'คนีขับรถเมาแล้วชนกับคนเดินในตลาดทำให้เกิดอุบัติเหตุรุนแรง ขณะที่กสุมาฉ้อโกงเงินผ่านระบบอิเล็กทรอนิกส์',
 'กิจหวังสร้างบริษัทปลอมรับบริจาคเงินช่วยผู้ป่วย ส่วนไค่แกล้งเป็นคนไข้ตัวอย่างที่ได้รับความช่วยเหลือ',
 'กุลรดียิงฆ่าผู้คนในงานกีฬา',
 'กชรตน์ใช้มีดโจมตีในงานเทศกาลจนเสียชีวิต',
 'กิตติฐานนท์ปลอมแฟนเพจแบรนด์ดังและมีเกษมบงกชช่วยผลิตสินค้าปลอมเพื่อหลอกขายสินค้าราคาถูกเกินจริง',
 'การติดตั้งหม้อแปลงไฟฟ้าโดยไม่ได้รับอนุญาตและไม่มีระบบป้องกันไฟฟ้ารั่ว ทำให้เกิดไฟไหม้โกดังจนมีผู้เสียชีวิต 2 ราย',
 'กิมเข่งติดตั้งชั้นวางผิดพลาด ทำให้พังลงมาใส่เด็กนักเรียนได้รับบาดเจ็บ',
 'กัลยณัฐฐ์ทะเลาะกับจุรีนาถเรื่องมรดกในบ้านพักและในช่วงอารมณ์รุนแรง เธอคว้าปืนจากลิ้นชักมายิงเขาจนเสียชีวิต',
 'กำสิทธิ์ดัดแปลงแก๊สหุงต้มด้วยความประมาทอวดเก่งในร้านอาหารเองโดยไม่ใช่ช่าง ทำให้เกิดระเบิดร้านและลูกค้าได้รับบาดเจ็บสาหัสหลายราย',
 'จอมภพใช้ปืนข่มขู่และชิงทรัพย์จากพนักงานในร้านค้า',
 'ขนิตตายิงปืนข่มขู่ในตลาดและขโมยของมีค่า',
 'คณินทิตาขโมยของจากร้านค้าโดยบุกรุกเข้ามาทางด้านหลังและใช้มีดข่มขู่กฤชตพลในงานเลี้ยง',
 'ข้าวโอ๊ดขับรถเมาในเทศกาลประชาชนและชนรถโดยสารที่เต็มไปด้วยผู้บริสุทธิ์ จนทำให้มีหลายคนเสียชีวิต',
 'จิตติวัตถ์ขโมยสินค้าและใช้ปืนข่มขู่ในงานแสดงสินค้าโดยบุกรุกเข้าไปโดยไม่ได้รับอนุญาต ขณะที่คำเนืองฉ้อโกงนักลงทุนในงานสัมมนา',
 'จิติรัตน์ใช้มีดแทงเกรียงไกรยุทธหลายครั้งที่บริเวณท้องในห้องครัวจนเธอเสียชีวิต',
 'เง็กสูนลอบบุกรุกเข้าห้องเก็บของในสำนักงานเพื่อขโมยแฟ้มลับ ขณะที่จิตรวัณใช้มีดข่มขู่ผู้คนในงานเลี้ยง',
 'คลอพรบุกรุกเข้าศูนย์การค้า ขโมยเงินสด แล้วยิงผู้ดูแลที่มาขัดขวาง',
 'คำบัวใช้หมวกกันน็อกฟาดศีรษะกัญจน์ทัสสิตาหลายครั้งอย่างจงใจขณะเขานั่งเล่นโทรศัพท์ จนเขาเสียชีวิต',
 'กุญนัดดาลอบบุกรุกเข้าบ้านเพื่อนแล้วขโมยกระเป๋าเงินในคืนวันหยุด ทำให้เจ้าของบ้านสูญเสียทรัพย์สิน',
 'จันทร์เทศฉ้อโกงเงินจากบริษัทด้วยเอกสารปลอมในงานจัดแสดงสินค้า และกัญณณัฐวรรณบุกรุกเข้าห้องประชุมเพื่อขโมยแฟ้มข้อมูล',
 'ขนมเทียนขโมยของจากงานเทศกาลกลางคืนโดยแอบบุกรุกเข้าร้านค้า',
 'เกสพิณญาบุกรุกเข้าบ้านพักของกาณฑ์กมลและขโมยของมีค่าออกไปในคืนวันหยุด',
 'จิธิยาขโมยกระเป๋าจากรถยนต์ในลานจอด',
 'กาณต์รวีแทงเจ้าของร้านอาหารระหว่างชิงทรัพย์จนเสียชีวิต',
 'จารุวัตขโมยทองคำจากตลาดและบุกรุกซอยหวงห้ามเพื่อหลบหนี',
 'ขวัญมัณฑนาหลอกขายของเล่นเด็กผ่านเพจเฟซบุ๊กโดยไม่มีการส่งสินค้าจริง',
 'คุณครูประจำชั้นอย่างคุ่ยเองถูกเด็กนักเรียนชายชื่อ กานดนันท์บ่นว่าโดนกดดันเกินไป แต่แทนที่จะรับฟัง คุ่ยเองล่อเด็กไปหลังห้องและใช้ของแข็งฟาดศีรษะเขาจนเสียชีวิต',
 'กมลาโสภิษฐ์เห็นพระเอกละครถูกฆ่าตาย',
 'กรณ์ธนะโชติใช้ค้อนทุบหลังศีรษะเกรียงฤทธิ์ซ้ำหลายครั้งจากด้านหลังในช่วงเขาไม่ทันระวัง จนเขาเสียชีวิต',
 'คุณกานต์โพสต์ขายรถยนต์ราคาต่ำผิดปกติ ส่วนกาญจนารีแกล้งเป็นคนที่ซื้อได้จริงและรีวิวหลอก',
 'คณิตกุลสวมบทเป็นคนส่งของ แล้ววางกล่องที่มีระเบิดไว้หน้าบ้านเกวาลีนจนเขาเปิดกล่องและเสียชีวิต',
 'จันทรัตน์เผลอทำมีดหล่นจากระเบียงคอนโด ทำให้มีดแทงกวิภัสที่เดินผ่านด้านล่างจนบาดเจ็บ',
 'กุลพัฒน์และขวัญวรัตน์เป็นชาวสวนที่ร่วมกันจัดอบรมเรื่องการปลูกพืชอินทรีย์ให้แก่เกษตรกรในพื้นที่',
 'กันยกรฐ์ในขณะไปงานแสดงศิลปะกลางแจ้ง ใช้ปืนยิงออกมาเพื่อขู่เข็ญผู้เข้าร่วมและในที่สุดได้ยิงฆ่าชาวบ้านที่อยู่ใกล้เคียงอย่างเด็ดขาด',
 'กณิตาและกลางชลชิงทรัพย์ร้านทองโดยใช้อาวุธปืน กุลนันต์แอบขโมยเครื่องเพชรในจังหวะชุลมุน',
 'กศิกัญจน์บุกรุกเข้าอาคารและขโมยสินค้าจากคลังสินค้า ขณะที่เกียรติกล้าขับรถเมาแล้วชนรถยนต์ ทำให้ผู้อื่นเสียทรัพย์สิน',
 'กานต์ฆฤทธิ์ขับรถโดยใช้โทรศัพท์มือถือไปด้วย ทำให้รถเสียหลักพุ่งชนคนเดินถนนคือคณิตสราจนเขาถึงแก่ความตาย',
 'จันเทศขับไล่ล่ารถของแฟนเก่าจนทำให้ชนคนอื่นเสียชีวิต',
 'จรูญเพชรใช้มีดโจมตีในการประท้วงแล้วยิงฆ่าผู้ชุมนุม',
 'จรรจวนฉ้อโกงนักลงทุนในโครงการธุรกิจด้วยเอกสารปลอมโดยมีจิตตินาร่วมขบวนการด้วย',
 'เกตช์นิภาอ้างตัวว่าเป็นผู้จัดหางานต่างประเทศและเก็บเงินค่าสมัครปลอมจากแรงงาน',
 'คุณชายประมาทวางท่อแก๊สเสียจนเกิดระเบิดในห้องแล็บ ทำให้ทรัพย์สินเสียหาย ขณะที่ฆนารสชิงทรัพย์อุปกรณ์กู้ภัยจากที่เกิดเหตุ',
 'คาฮุ้งยิงปืนและฆ่าผู้คนในงานแข่งรถ',
 'กฤษติณาฉ้อโกงเงินจากประชาชนผ่านเว็บไซต์ปลอม',
 'กิติร์อ้างเป็นตัวแทนอสังหาริมทรัพย์หลอกให้วางเงินจองบ้านโครงการปลอม',
 'กุลติมาใช้ไขควงงัดหน้าต่างบ้านเกร็ดจุฑาและขู่ลูกเขาด้วยมีดพก ก่อนจะทำร้ายเล็กน้อย',
 'จันทร์สมัยใช้ปืนข่มขู่ขณะบุกรุกร้านและยิงฆ่าผู้พิทักษ์',
 'เกรียงพันธ์วางยาพิษใส่อาหารของสามีจนเขาเสียชีวิต',
 'กาขับรถเร็วเกินกฎหมายกำหนดในหมู่บ้าน ทำให้เสียหลักชนรั้วบ้านของเกษวัต',
 'จิราเมศร์บุกรุกเข้าที่ประชุมแล้วขโมยเอกสารสำคัญ',
 'จรินทร์เลิศขับรถสวนเข้ามาในสนามแข่งโดยไม่มีใบอนุญาตแต่ไม่ได้ตั้งใจกระทำผิด',
 'เกรียงพันธ์ฉ้อโกงเงินจากผู้ลงทุนผ่านเว็บไซต์ปลอมและใช้มีดข่มขู่ในงานแฟร์ ทำให้ผู้ร่วมงานตกใจ และคุณยงขโมยโทรศัพท์มือถือในช่วงชุลมุน',
 'กำไรทิพย์จัดฉากให้ดูเหมือนอุบัติเหตุ โดยผลักเจ๊ะหีมลงบันไดหลายขั้นขณะเธอถือของ ทำให้เธอกระแทกพื้นและเสียชีวิต',
 'เกษรินทร์ติดตั้งระเบิดขนาดเล็กไว้ใต้เบาะรถของครินทร์และตั้งเวลาไว้ให้ระเบิดขณะเขากำลังขับรถ ส่งผลให้เขาเสียชีวิตทันที',
 'จิตร์เจริญขโมยเงินสดจากตู้เอทีเอ็มผ่านการบุกรุก',
 'กัณฐาภรณ์แอบซ่อนมีดไว้ในกล่องของขวัญวันเกิดให้กับกฤตภัทรและใช้โอกาสขณะแกะของแทงเขาจนเสียชีวิต',
 'หลังจากจำเลือง ตื่นจากการสลบ ก็พบร่าง กุลทิณี ถูกปาดคอ เต็มไปด้วยเลือด คณิวัฒน์ที่เป็นฆาตรกรตัวจริง ก็ปรากฎตัว แล้วทำตัวเป็นพยานว่าจำเลือง เป็นฆาตรกร',
 'กรปรียาใช้ปืนข่มขู่ขณะบุกรุกเข้าบ้านเพื่อชิงทรัพย์ออกไป',
 'กรานติ์ขับรถพุ่งเข้าร้านขายยาเนื่องจากความประมาท ทำให้มีผู้บาดเจ็บและทรัพย์สินเสียหาย ขณะเขมภณฉวยโอกาสขโมยยา',
 'กัญณีย์อุทานว่า อุ๊ย ตายแล้ว',
 'เกตุจรินทร์ทำตัวเหมือนคนที่ยังรักคนิจและชวนเธอไปที่ทะเล ก่อนจะพาเธอลงเรือแล้วดึงให้เธอตกน้ำ ใช้เท้ากดเธอไว้ใต้น้ำจนเธอถึงแก่ความตาย',
 'จาตุกรณ์ซักผ้าพรมแล้วนำไปวางตากในบันไดหนีไฟ ทำให้คนลื่นล้ม',
 'เกษวรินทร์เข้าไปซื้อข้าวในโรงอาหาร แล้วมานั่งกินชิลๆกับเพื่อนๆ',
 'จุณีย์เป็นผู้ดูแลศูนย์ฝึกอาชีพที่เชิญขึ้นมาช่วยเป็นวิทยากรสอนทำอาหารให้กับผู้พิการที่ต้องการประกอบอาชีพอิสระ',
 'จันทร์บางถือปืนข่มขู่พนักงานธนาคารแล้วขโมยเงินสดจากตู้เอทีเอ็ม',
 'ในงานมูลนิธิการกุศล ณ ศูนย์ประชุมใหญ่ กิตติ์วัฒน์แอบเนียนขโมยเงินจากตู้บริจาคคณะที่กำลังเปิดพิธี',
 'กฤตญาณิญญ์ทำงานผิดพลาดปล่อยสารเคมีในโรงงานจนทำให้เพื่อนร่วมงานบาดเจ็บ ส่วนจันทร์ธณาใช้โอกาสลอบขโมยอุปกรณ์วิจัย',
 'กาญจน์พิพัฒน์ยิงปืนข่มขู่และชิงของมีค่าในศูนย์การค้า',
 'กงแงจวนลอบเข้าไปในบ้านของขวัญไชย์แล้วใช้มีดทำครัวแทงเขาบริเวณแขนขวา เพราะมีปัญหาส่วนตัวกัน',
 'กัณฑารัตน์ขโมยเงินจากตู้เอทีเอ็มผ่านบุกรุกเข้ามาทางด้านหลังธนาคารในตอนกลางคืน โดยเจาะประตูของธนาคารเสียหาย',
 'กระแสสินธุ์แกล้งทำเป็นห่วงกิตตินัยที่อยู่ในอาการซึมเศร้า แต่จริง ๆ แล้วเธอผลักเขาลงจากดาดฟ้าให้ดูเหมือนฆ่าตัวตายจนเขาเสียชีวิต',
 'กษิดิศฐิติบุญละเลยไม่ปิดฝาท่อที่เปิดทิ้งไว้ในไซต์งานก่อสร้าง ทำให้จิรัฎฎฐ์ตกท่อได้รับบาดเจ็บสาหัส',
 'คนึงณัฐปล่อยให้ไฟฟ้ารั่วในเครื่องอบผ้าแล้วให้ เกษรักณ์ใช้งานจนช็อตเสียชีวิต',
 'คงวัตรขโมยของมีค่าจากห้างสรรพสินค้าด้วยการบุกรุกทางด้านหลังในตอนเที่ยงคืน',
 'จรรยาณีขับรถเมาแล้วชนคนเดินเท้าในชุมชน ทำให้อุบัติเหตุร้ายแรงเกิดขึ้น',
 'จันทร์ตุ้ยฉ้อโกงเงินจากนักลงทุนในโครงการปลอมทำให้หลายคนสูญเสียเงิน',
 'เจียรผจงเสนอขายแพ็กเกจทัวร์ต่างประเทศราคาถูก ส่วนกัณศักดิ์แกล้งเป็นลูกค้าที่ได้เที่ยวจริง',
 'แกมแก้วขโมยสินค้าจากตลาดนัดด้วยการบุกรุกทางหลัง',
 'คุรกิรปาลซิงห์ขโมยสมุดจากสถานศึกษาโดยบุกรุกเข้าห้องเรียน',
 'ขิมณัฐลอบบุกรุกโรงแรมและขโมยของจากตู้อัตโนมัติ',
 'กิตติสวัสดิ์ใช้ความรุนแรงข่มขู่พนักงานธนาคารให้โอนเงิน ขณะเกรียงชายปลอมเอกสารโอนเงินเพื่อปกปิดการกระทำ',
 'กีส์ฎาใช้ปืนข่มขู่และขโมยเครื่องประดับในงานเลี้ยง',
 'กมลชาญยิงเจ้าหน้าที่รักษาความปลอดภัยจนเสียชีวิตและขโมยปืนจากศพ ขณะคณัฐน์ขโมยกระเป๋าเงินในจุดเกิดเหตุ',
 'โกรินทรนาบุกรุกเข้าห้องเก็บของในโรงงานและขโมยข้อมูลลับ',
 'เกรียงมนต์เมาแล้วขับชนท้ายรถของคนิษฐ์ที่จอดติดไฟแดง จนคนิษฐ์บาดเจ็บสาหัส',
 'เกสนาขับรถเมาจนชนรถรับจ้างบนถนนจนเกิดอุบัติเหตุรุนแรง',
 'จิตรศราวุฒิกับเกล็ดเดินเข้างานเลี้ยงขนาดใหญ่ที่จัดขึ้นในโรงแรมหรูและขโมยของมีค่า พร้อมกับยิงฆ่าผู้เข้าร่วมงานที่เห็นเหตุการณ์',
 'จันทร์ริยาเป็นนักจัดรายการวิทยุชื่อดัง แต่ฆ่าคงศิลป์ซึ่งเป็นผู้ฟังที่โทรมาขู่ว่าจะเปิดโปงความลับอันดำมืด ด้วยการล่อเธอไปที่ห้องอัดเก่าก่อนแล้วรัดคอจนเสียชีวิต',
 'การัณยวีร์ที่มาจากไหนก็ไม่รู้ยิงตำรวจจนเสียชีวิตหลังเกิดเหตุปล้นร้านทอง ขณะจินทนาลักเครื่องประดับหลบหนี โดยที่มาทราบทีหลังว่าสองคนนี้ไม่ได้ร่วมมือกัน',
 'จารุวัลลภ์ใช้ปืนข่มขู่พนักงานธนาคารเพื่อชิงเงินสด ขณะที่จตุฬสหลอกลวงลูกค้าผ่านเว็บไซต์ปลอมเพื่อฉ้อโกง',
 'ฆีบธเศษฐ์ลอบแทงเก๊าจ้วยจากด้านหลังในขณะที่เขากำลังอาบน้ำจนเสียชีวิต',
 'กอบรัตน์ปลอมเอกสารราชการเพื่อรับเงินเบี้ยยังชีพ และขโมยข้อมูลประชาชนจากระบบเทศบาล ส่วนจีรณพัตลักลอบเข้าออฟฟิศตอนกลางคืน',
 'ขาเกียววางแผนล่อให้กิมโม่ยขึ้นรถไปยังที่เปลี่ยว แล้วใช้ก้อนหินทุบศีรษะจนเสียชีวิต',
 'กัญญรัศมิ์ยิงหัวหน้าแผนกจนเสียชีวิต ขณะที่จิตนาภรณ์ชิงทรัพย์แฟ้มธุรกิจออกจากออฟฟิศ',
 'เกศดาพรขโมยเงินสดจากตู้อัตโนมัติในห้างและพังทุบประตูบ้านคนในท้องถิ่นจนพังเสียหายเพื่อขโมยของออกไป ขณะที่กิจดีฉ้อโกงผ่านโทรศัพท์',
 'เง็กซัวทะเลาะกับจัตุพลจนมีเรื่องบาดหมางกันนิดหน่อย',
 'จิรัศวดีฐ์ฉ้อโกงเงินจากนักลงทุนผ่านการส่งเอกสารปลอมและบุกรุกเข้าห้องประชุมเพื่อขโมยแฟ้มลับ ขณะที่จันทิตย์ขโมยโทรศัพท์มือถือจากผู้โดยสาร',
 'กาสารงัดประตูบ้านของคำณวนเข้าไปขโมยเครื่องใช้ไฟฟ้า ขณะที่เจียงศรใช้ปืนขู่เจ้าของบ้านให้เปิดตู้นิรภัย',
 'จิตตนาวันลอบบุกรุกเข้าห้องเก็บของในอาคารและขโมยของมีค่าออกไปอย่างชัดเจน ขณะที่จุรารัตร์เป็นพยาน',
 'จงปราณีย์ขับรถตัดหน้ากะทันหันจนเกิดอุบัติเหตุรุนแรง ขณะครรลองขโมยของจากรถคู่กรณี',
 'เจตษฎาลอบบุกรุกเข้าห้องประชุมในสำนักงานและขโมยแฟ้มลับออกไป ขณะที่จิตฑิมาฉ้อโกงเงินจากระบบออนไลน์',
 'กัญญ์ฐิภัสส์หลอกให้จันหอมขึ้นไปซ่อมหลังคาบ้าน แล้วผลักเขาตกลงมาศีรษะกระแทกพื้นเสียชีวิต',
 'จิราวลัยขโมยของจากร้านค้าปลีกโดยบุกรุกเข้ามาทางด้านหลัง',
 'กุณทรัตน์ยิงกวินทร์วัตน์ด้วยปืนพกที่ศีรษะหนึ่งนัดจนเสียชีวิต',
 'ขันฑ์โชติถูกจับตัวขณะพยายามขโมยเงินสดจากตู้เอทีเอ็มในธนาคารแห่งหนึ่งในเช้าวันใหม่ โดยที่เขาได้บุกรุกเข้ามาผ่านหน้าต่างที่ถูกเปิดทิ้งไว้โดยเจตนา',
 'จตุรพรบุกรุกอาคารและขโมยของมีค่า',
 'จิตภาภรณ์วางแก๊สพิษไว้ในห้องนอนแล้วตั้งเวลาเปิดตอนกลางคืน ทำให้กรุตสูดดมเข้าไปและเสียชีวิต',
 'จิตวิฑูรย์ลอบบุกรุกเข้าสวนหย่อมส่วนตัวของกิตติกำธรและขโมยของมีค่าออกไปในเวลาที่กิตติกำธรไม่อยู่บ้าน',
 'ในงานเลี้ยง ณ ร้านอาหารหรู กรุงโกสินทร์ขโมยเงินจากแขกและยิงฆ่าพนักงานที่พยายามจับกุม',
 'เกื้อสกุลบุกรุกเข้าห้องเก็บแฟ้มในธนาคารเพื่อขโมยสมุดบัญชี ขณะที่ฆโณทัยปลอมลายเซ็นลูกค้าเพื่อโอนเงินฉ้อโกง',
 'กุลาภาขับรถเร็วในทางโค้งและเสียหลักไปชนรถของคีโรชาที่ขับย้อนศรมา ทั้งคู่ได้รับบาดเจ็บและทำให้ทรัพย์สินของร้านค้าริมถนนเสียหาย',
 'กัญภาธินไม่ติดป้ายเตือนพื้นที่ลื่น ทำให้คนเดินล้ม',
 'กุลวราขโมยเครื่องประดับจากร้านเครื่องประดับในเวลากลางคืนด้วยการบุกรุก',
 'แก้วพรมมาขับรถเมาประมาทชนกับรถส่วนตัวในตรอกเล็กจนเกิดเหตุร้ายแรงซึ่งเป็นเหตุให้จินานันท์เสียชีวิต',
 'จีรณินทร์ฉ้อโกงลูกค้าด้วยการปลอมตัวเป็นเจ้าหน้าที่ธนาคารในระบบออนไลน์',

In [13]:
train_labels_for_hf

[[0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
 [0.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0],
 [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],
 [0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0],

In [14]:
# --- 3. Import Hugging Face Libraries ---
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    AutoConfig,
    Trainer,
    TrainingArguments,
)

In [15]:
from datasets import Dataset, DatasetDict
import evaluate
import numpy as np
import torch # For a multi-label problem, BCEWithLogitsLoss is common

In [16]:
# --- 4. Load Pretrained Model, Tokenizer, Config ---
model_name = 'clicknext/phayathaibert' # Or another suitable Thai model
num_classes = 8 # Based on your class_df (0-7)

# For multi-label classification, you often need to set problem_type
config = AutoConfig.from_pretrained(
    model_name,
    num_labels=num_classes,
    problem_type="multi_label_classification" # IMPORTANT for multi-label
)
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name, config=config)

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/642 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/527 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.26M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/15.0k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/364 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

Some weights of CamembertForSequenceClassification were not initialized from the model checkpoint at clicknext/phayathaibert and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [17]:
# --- 5. Create DatasetDict ---
# Create a dictionary for the training data
train_data_dict = {'text': train_texts, 'labels': train_labels_for_hf}
hf_train_dataset = Dataset.from_dict(train_data_dict)

In [18]:
# (Create hf_dev_dataset and hf_test_dataset similarly if you have them)
# For now, let's assume you'll split train or use a separate dev file
# Example: if creating a dev set from train_df
# dev_texts = ...
# dev_labels_for_hf = ...
# hf_dev_dataset = Dataset.from_dict({'text': dev_texts, 'labels': dev_labels_for_hf})

dataset_dict_content = {'train': hf_train_dataset}
# if hf_dev_dataset:
#     dataset_dict_content['dev'] = hf_dev_dataset
# if hf_test_dataset: # If you have ground truth for test for evaluation
#     dataset_dict_content['test'] = hf_test_dataset

d = DatasetDict(dataset_dict_content)
d

DatasetDict({
    train: Dataset({
        features: ['text', 'labels'],
        num_rows: 1800
    })
})

In [19]:
print(d)
print(d['train'][0])

DatasetDict({
    train: Dataset({
        features: ['text', 'labels'],
        num_rows: 1800
    })
})
{'text': 'จุงลิ่วขโมยรถจักรยานยนต์จากลานจอด ขณะที่แคสใช้ปืนจี้ชิงเงินสดจากสถานีขนส่ง', 'labels': [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0]}

In [20]:
# --- 6. Tokenization Function and Mapping ---
def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=128) # Adjust max_length

tokenized_datasets = d.map(tokenize_function, batched=True)
tokenized_datasets

Map:   0%|          | 0/1800 [00:00<?, ? examples/s]

DatasetDict({
    train: Dataset({
        features: ['text', 'labels', 'input_ids', 'attention_mask'],
        num_rows: 1800
    })
})

In [21]:
# Access an element from the 'train' split
tokenized_datasets['train'][0]

{'text': 'จุงลิ่วขโมยรถจักรยานยนต์จากลานจอด ขณะที่แคสใช้ปืนจี้ชิงเงินสดจากสถานีขนส่ง',
 'labels': [0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0],
 'input_ids': [5,
  10,
  7364,
  15948,
  2648,
  3026,
  1398,
  32,
  2707,
  2373,
  2117,
  10773,
  15495,
  2652,
  1895,
  3901,
  32,
  17646,
  6,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0]}

In [22]:
# --- 7. Define TrainingArguments ---
training_args = TrainingArguments(
    output_dir='./results_legal',
    num_train_epochs=3, # Adjust as needed
    per_device_train_batch_size=16, # Adjust based on GPU memory
    per_device_eval_batch_size=16,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs_legal',
    logging_steps=100,
    eval_strategy="epoch", # Changed from evaluation_strategy to eval_strategy
    # eval_steps=500, # if eval_strategy="steps"
    save_strategy="epoch",
    load_best_model_at_end=True, # If using eval_strategy
    metric_for_best_model="f1", # For multi-label, f1-micro or f1-macro is common
    report_to="wandb" # or "none"
)

In [23]:
# --- 8. Define compute_metrics Function (for multi-label) ---
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score
from transformers import EvalPrediction
import torch

def multi_label_metrics(predictions, labels, threshold=0.5):
    # first, use sigmoid on predictions which are logits
    sigmoid = torch.nn.Sigmoid()
    probs = sigmoid(torch.Tensor(predictions))
    # next, use threshold to turn them into integer predictions
    y_pred = np.zeros(probs.shape)
    y_pred[np.where(probs >= threshold)] = 1
    # finally, compute metrics
    y_true = labels
    f1_micro_average = f1_score(y_true=y_true, y_pred=y_pred, average='micro')
    roc_auc = roc_auc_score(y_true, y_pred, average = 'micro') # Requires probabilities for proper AUC
    accuracy = accuracy_score(y_true, y_pred)
    # return as dictionary
    metrics = {'f1': f1_micro_average,
               'roc_auc': roc_auc,
               'accuracy': accuracy}
    return metrics

def compute_metrics(p: EvalPrediction):
    preds = p.predictions[0] if isinstance(p.predictions, tuple) else p.predictions
    result = multi_label_metrics(
        predictions=preds,
        labels=p.label_ids)
    return result

In [24]:
# --- 5. Create DatasetDict ---
# Create a dictionary for the training data
train_data_dict = {'text': train_texts, 'labels': train_labels_for_hf}
hf_full_dataset = Dataset.from_dict(train_data_dict)

# Split the dataset into training and evaluation sets
# Adjust the test_size (e.g., 0.1 or 0.2 for 10% or 20% evaluation set)
split_datasets = hf_full_dataset.train_test_split(test_size=0.2)

dataset_dict_content = {
    'train': split_datasets['train'],
    'eval': split_datasets['test'] # Use 'eval' as the key for the evaluation set
}

d = DatasetDict(dataset_dict_content)
print(d) # Verify that 'train' and 'eval' keys exist
print(d['train'][0]) # Check a sample from the training set
print(d['eval'][0])  # Check a sample from the evaluation set

# --- 6. Tokenization Function and Mapping ---
def tokenize_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=128) # Adjust max_length

# Apply tokenization to the split datasets
tokenized_datasets = d.map(tokenize_function, batched=True)
tokenized_datasets

# --- 7. Define TrainingArguments ---
training_args = TrainingArguments(
    output_dir='./results_legal',
    num_train_epochs=3, # Adjust as needed
    per_device_train_batch_size=16, # Adjust based on GPU memory
    per_device_eval_batch_size=16,
    warmup_steps=500,
    weight_decay=0.01,
    logging_dir='./logs_legal',
    logging_steps=100,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    report_to="wandb" # or "none"
)

# --- 8. Define compute_metrics Function (for multi-label) ---
from sklearn.metrics import f1_score, roc_auc_score, accuracy_score
from transformers import EvalPrediction
import torch

def multi_label_metrics(predictions, labels, threshold=0.5):
    # first, use sigmoid on predictions which are logits
    sigmoid = torch.nn.Sigmoid()
    probs = sigmoid(torch.Tensor(predictions))
    # next, use threshold to turn them into integer predictions
    y_pred = np.zeros(probs.shape)
    y_pred[np.where(probs >= threshold)] = 1
    # finally, compute metrics
    y_true = labels
    # Use zero_division=0 to handle cases where no true or predicted labels exist for a class
    f1_micro_average = f1_score(y_true=y_true, y_pred=y_pred, average='micro', zero_division=0)
    # roc_auc_score requires probabilities, not binary predictions
    # Ensure y_true has at least two classes for ROC AUC calculation
    if np.unique(y_true).shape[0] > 1:
        roc_auc = roc_auc_score(y_true, probs, average = 'micro')
    else:
        # Handle cases with only one class in the batch/dataset
        roc_auc = 0.0
        print("Warning: Only one class present in true labels for ROC AUC calculation.")

    accuracy = accuracy_score(y_true, y_pred)
    # return as dictionary
    metrics = {'f1': f1_micro_average,
               'roc_auc': roc_auc,
               'accuracy': accuracy}
    return metrics

def compute_metrics(p: EvalPrediction):
    preds = p.predictions[0] if isinstance(p.predictions, tuple) else p.predictions
    result = multi_label_metrics(
        predictions=preds,
        labels=p.label_ids)
    return result

# --- 9. Initialize Trainer ---
from transformers import DataCollatorWithPadding
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    # Pass the evaluation dataset using the 'eval' key
    eval_dataset=tokenized_datasets["eval"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

# --- 10. Start Training ---
# Now the 'eval' dataset exists, so training with evaluation will proceed
trainer.train()

DatasetDict({
    train: Dataset({
        features: ['text', 'labels'],
        num_rows: 1440
    })
    eval: Dataset({
        features: ['text', 'labels'],
        num_rows: 360
    })
})
{'text': 'เจตต์ชัญญาวางยาพิษในอาหารของสามีจนเสียชีวิต เพื่อหวังเงินประกันชีวิต', 'labels': [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0]}
{'text': 'คชรักไม่ตรวจสอบความปลอดภัยก่อนให้ขึ้นลิฟต์ ทำให้ลิฟต์ตก มีผู้เสียชีวิต', 'labels': [0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]}

Map:   0%|          | 0/1440 [00:00<?, ? examples/s]

Map:   0%|          | 0/360 [00:00<?, ? examples/s]

<ipython-input-24-103ac2f48eb2>:88: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(
wandb: WARNING The `run_name` is currently set to the same value as `TrainingArguments.output_dir`. If this was not intended, please specify a different run name by setting the `TrainingArguments.run_name` parameter.

wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter:

 ··········

wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: ratchanon-faust (ratchanon-faust-khon-kaen-university) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

TrainOutput(global_step=270, training_loss=0.36426290582727505, metrics={'train_runtime': 277.9087, 'train_samples_per_second': 15.545, 'train_steps_per_second': 0.972, 'total_flos': 284175247933440.0, 'train_loss': 0.36426290582727505, 'epoch': 3.0})

In [25]:
# prompt: predict test

import numpy as np
# Assuming 'trainer' object is already trained and available

# --- 11. Prepare Test Data for Prediction ---
# Get the text stories from the test DataFrame
test_texts = test_df['story'].tolist()

# Create a Hugging Face Dataset for the test data
# The test dataset doesn't have ground truth labels for prediction purposes
test_data_dict = {'text': test_texts}
hf_test_dataset = Dataset.from_dict(test_data_dict)

# Tokenize the test dataset
tokenized_test_datasets = hf_test_dataset.map(tokenize_function, batched=True)

# --- 12. Make Predictions on the Test Set ---
# Use the trained trainer to predict on the tokenized test dataset
predictions = trainer.predict(tokenized_test_datasets)

# 'predictions' object contains predictions, label_ids (None for test), and metrics
# Access the logits (raw output before activation)
logits = predictions.predictions

# Apply sigmoid to the logits to get probabilities for multi-label classification
sigmoid = torch.nn.Sigmoid()
probabilities = sigmoid(torch.Tensor(logits)).numpy() # Convert to NumPy array

# Apply a threshold to get binary predictions (0 or 1)
# A common threshold is 0.5, but this can be tuned
threshold = 0.5
binary_predictions = np.zeros(probabilities.shape)
binary_predictions[np.where(probabilities >= threshold)] = 1

# --- 13. Format Predictions for Submission (Optional, depends on submission format) ---
# If you need to output the predicted class IDs for each story, you can do so
# The binary_predictions array has a row for each story and a column for each class (0-7)

predicted_classes = []
for row in binary_predictions:
    # Get the indices where the prediction is 1
    predicted_class_indices = np.where(row == 1)[0].tolist()
    predicted_classes.append(predicted_class_indices)

# Add the predicted classes back to the test_df if needed
test_df['predicted_labels'] = predicted_classes

# You can now inspect test_df or save it
print(test_df[['story', 'predicted_labels']].head())

# You might need to format the predicted_labels column according to the competition's
# submission file requirements (e.g., specific string format).

Map:   0%|          | 0/1000 [00:00<?, ? examples/s]

                                               story predicted_labels
0   เคี้ยนแพ้หมากรุกเลยชักปืนขึ้นมายิงจราจนเสียชีวิต        [1, 5, 7]
1                     จิดาพัฒน์ยิงปืนเล่นน้ำสงกรานต์              [1]
2  กรัณยพรขับรถเมาแล้วชนรถบัสในสถานีขนส่ง ส่งผลให...           [3, 7]
3  คำนึงภัชทุจริตในการจัดซื้อวัสดุโรงเรียนและปลอม...           [2, 6]
4  กอบเกิดขับรถขณะหลับในช่วงกลางวัน ทำให้รถพุ่งข้...           [3, 7]

In [26]:
test_df

,id,story,answers,parsed_labels,predicted_labels
0,XwlpP5otmI,เคี้ยนแพ้หมากรุกเลยชักปืนขึ้นมายิงจราจนเสียชีวิต,"[{'เคี้ยน': '[5,7]'}, {'จรา': '[1]'}]","[1, 5, 7]","[1, 5, 7]"
1,1pUXZYyXqQ,จิดาพัฒน์ยิงปืนเล่นน้ำสงกรานต์,[{'จิดาพัฒน์': '[1]'}],[1],[1]
2,drf7jObOL3,กรัณยพรขับรถเมาแล้วชนรถบัสในสถานีขนส่ง ส่งผลให...,"[{'กรัณยพร': '[3,7]'}]","[3, 7]","[3, 7]"
3,ghD7Mhgjsq,คำนึงภัชทุจริตในการจัดซื้อวัสดุโรงเรียนและปลอม...,NaN,[],"[2, 6]"
4,5lfeF2x61n,กอบเกิดขับรถขณะหลับในช่วงกลางวัน ทำให้รถพุ่งข้...,NaN,[],"[3, 7]"
...,...,...,...,...,...
995,wEWpIvFoB9,กิมฮัวฉ้อโกงเงินจากลูกค้าผ่านเว็บไซต์ปลอมในงาน...,NaN,[],[6]
996,JbSegK5ioA,กุศลินีบุกรุกเข้าโรงพยาบาล ขโมยยาและทำร้ายพยาบ...,NaN,[],"[2, 4, 5]"
997,3cnDAIVegR,กลินธ์ขับรถประมาทในการแข่งจนเกิดอุบัติเหตุร้ายแรง,NaN,[],[3]
998,JCTioVnnxg,กชญาณสร้างบริษัทอสังหาริมทรัพย์ปลอม ส่วนจิราทิ...,NaN,[],[6]
999,cqa6LAhrPL,เกษฉราภรณ์ขับรถเมาแล้วชนคนเดินเท้าในซอย,NaN,[],[3]